### Create user
POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Joao",
  "email": "joao@gmail.com",
  "password": "123456"
}

### Authenticate
POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email": "ze@gmail.com",
  "password": "123456"
}

### Create Restaurant
POST http://localhost:3333/restaurants
Content-Type: application/json
x-user-id: 39b1a102-760a-47aa-a0db-6b9bace42e46

{
  "name": "Restaurant Fabio",
  "logo": null,
  "primaryColor": "#C0392B",
  "settings": {
    "slots": [
      { "from": "18:00", "to": "20:00", "maxReservations": 10 },
      { "from": "20:00", "to": "22:00", "maxReservations": 20 }
    ]
  }
}

### Create Reservation
POST http://localhost:3333/reservations
Content-Type: application/json

{
  "restaurantId": "d6d5cac7-e249-441e-8ca3-c5f560ffde70",
  "date": "2025-11-10T18:00:00.000Z",
  "time": "20:22",
  "customerName": "Luis",
  "customerEmail": "luis@example.com",
  "groupSize": 2
  }


### Cancel Reservation
PATCH http://localhost:3333/reservations/2f1e1d13-d3f9-4b0e-b43e-12135a049bdc/cancel
