### Create user
POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Joao",
  "email": "joao@gmail.com",
  "password": "123456"
}

### Authenticate
POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email": "ze@gmail.com",
  "password": "123456"
}

### Create Restaurant
POST http://localhost:3333/restaurants
Content-Type: application/json
x-user-id: 39b1a102-760a-47aa-a0db-6b9bace42e46

{
  "name": "Restaurant 3",
  "logo": null,
  "primaryColor": "#C0392B",
  "settings": {}
}
