@baseUrl = http://localhost:3333
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmMTIxOTQ1ZS01NTFiLTQ3YWEtOGRjOC00MDFiY2M2MTA1NzUiLCJyZXN0YXVyYW50SWQiOiJiNDYwMTljMC03NDczLTQxYTYtOTU3ZS1kYjgyZDEwNDI0ZGIiLCJlbWFpbCI6Im1vdGFAZ21haWwuY29tIiwibmFtZSI6Ik1vdGEiLCJpYXQiOjE3NjI5NzgxNTF9.C4pH9k6-CbzLuN_fo3frTeIXqOOUpeyJLcSfknB9O1w
@restaurantId = b46019c0-7473-41a6-957e-db82d10424db
@otherRestaurantId = 240a299b-0757-4609-83e0-ca1ca3b9cbac
@reservationId = 20c2d9e7-6587-4299-9083-ff07d660c904

### Create user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Mota",
  "email": "mota@gmail.com",
  "password": "123456"
}

### Authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "mota@gmail.com",
  "password": "123456"
}

### Create Restaurant
POST {{baseUrl}}/restaurants
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Restaurant da Sabores",
  "logo": null,
  "primaryColor": "#C0392B",
  "settings": {
    "closedWeekly": [{ "weekday": 1, "from": "12:00", "to": "15:00" }],
    "closedDates": [{ "date": "2025-12-25", "from": "18:00", "to": "23:59" }],
    "slots": [
      { "from": "12:00", "to": "12:00", "maxReservations": 20 },
      { "from": "13:00", "to": "14:00", "maxReservations": 20 },
      { "from": "18:00", "to": "20:00", "maxReservations": 20 },
      { "from": "20:00", "to": "22:00", "maxReservations": 20 }
    ]
  }
}

### Re-authenticate after creating restaurant
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "mota@gmail.com",
  "password": "123456"
}

### Create Reservation
POST {{baseUrl}}/reservations
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "restaurantId": "{{restaurantId}}",
  "date": "2025-11-20T18:00:00.000Z",
  "time": "19:22",
  "customerName": "Julio",
  "customerEmail": "julio@example.com",
  "groupSize": 5
  }


### Cancel Reservation
PATCH {{baseUrl}}/reservations/{{reservationId}}/cancel
Authorization: Bearer {{token}}

### List reservations for a specific date
GET {{baseUrl}}/restaurants/{{restaurantId}}/reservations?date=2025-11-19
Accept: application/json
Authorization: Bearer {{token}}


### Should be 401 without token
GET {{baseUrl}}/restaurants/{{restaurantId}}/reservations
Accept: application/json

### Should be 403 with token for a DIFFERENT restaurantId
GET {{baseUrl}}/restaurants/{{otherRestaurantId}}/reservations
Accept: application/json
Authorization: Bearer {{token}}

### List upcoming reservations: Should work with correct owner token + restaurantId
GET {{baseUrl}}/restaurants/{{restaurantId}}/reservations
Accept: application/json
Authorization: Bearer {{token}}
